/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlxe;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class QuanlyXe extends javax.swing.JFrame {

    /**
     * Creates new form QuanlyXe
     */
    public QuanlyXe() {
        initComponents();
        ShowTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTmaxe = new javax.swing.JTextField();
        jTtenxe = new javax.swing.JTextField();
        jThangxe = new javax.swing.JTextField();
        jTgiathanh = new javax.swing.JTextField();
        jBthem = new javax.swing.JButton();
        jBsua = new javax.swing.JButton();
        jBxoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTtimkiem = new javax.swing.JTextField();
        jBlammoi = new javax.swing.JButton();
        jBtimkiem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTqlxe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        jLabel1.setText("Mã Xe:");

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        jLabel2.setText("Tên Xe:");

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        jLabel3.setText("Hãng Xe:");

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        jLabel4.setText("Giá Thành:");

        jBthem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBthem.setText("Thêm");
        jBthem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBthemMouseClicked(evt);
            }
        });

        jBsua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBsua.setText("Sửa");
        jBsua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBsuaMouseClicked(evt);
            }
        });

        jBxoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBxoa.setText("Xóa");
        jBxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBxoaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tìm kiếm theo tên:");

        jBlammoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBlammoi.setText("Làm Mới");
        jBlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlammoiActionPerformed(evt);
            }
        });

        jBtimkiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtimkiem.setText("Tìm Kiếm");
        jBtimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtimkiemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("QUẢN LÝ XE");

        jTqlxe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Xe", "Tên Xe", "Hãng Xe", "Giá Thành"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTqlxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTqlxeMouseClicked(evt);
            }
        });
        jTqlxe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTqlxeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTqlxe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTmaxe, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(jTtenxe)
                                .addComponent(jThangxe)
                                .addComponent(jTgiathanh))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBthem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jBsua)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jBxoa))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(jBlammoi)
                                    .addGap(36, 36, 36)
                                    .addComponent(jBtimkiem))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(264, 264, 264)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTmaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTtenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jThangxe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTgiathanh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBthem)
                            .addComponent(jBsua)
                            .addComponent(jBxoa))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBlammoi)
                            .addComponent(jBtimkiem))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsuaMouseClicked
        // TODO add your handling code here:
        try {
            if (check(jTmaxe.getText()) == true) {
            //txt_maSP.setEnabled(false)
                suaDL();
                ShowTable();
                JOptionPane.showMessageDialog(null, "Bạn đã cập nhật thành công!");
            } else {
                JOptionPane.showMessageDialog(null, "Mã sản phẩm không trùng với dữ liệu cần sửa!");
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanlyXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jBsuaMouseClicked

    
    private void jTqlxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTqlxeMouseClicked
        // TODO add your handling code here:
        Show_Detail();
    }//GEN-LAST:event_jTqlxeMouseClicked
    
    private void jBthemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBthemMouseClicked
        // TODO add your handling code here:
        jTmaxe.setEnabled(true);
        String maxe = jTmaxe.getText();
        String tenxe = jTtenxe.getText();
        String hangxe = jThangxe.getText();
        String giathanh = jTgiathanh.getText();
        maxe = maxe.replaceAll(" ", "");
        tenxe = tenxe.replaceAll(" ", "");
        hangxe = hangxe.replaceAll(" ", "");
        giathanh = giathanh.replaceAll(" ", "");
        if (jTmaxe.getText().equals("") == true || jTtenxe.equals("") == true || jTgiathanh.equals("") == true) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập dữ liệu!");
        } else {
            try {
                if (check(maxe) == true) {
                    JOptionPane.showMessageDialog(null, "Mã sản phẩm bị trùng!!! Vui lòng nhập lại!!!");
                } else {
                    Insert();
                    ShowTable();
                    JOptionPane.showMessageDialog(null, "Đã thêm thành công");
                    
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(QuanlyXe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBthemMouseClicked

    private void jBxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBxoaActionPerformed
        // TODO add your handling code here:
        String maxe = jTmaxe.getText();
        try {
            if (check(maxe) == true) {
                int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa sản phẩm này không", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    Delete(maxe);
                    ShowTable();
                } else {
                }
            } else {
                JOptionPane.showMessageDialog(null, "Mã sản phẩm không trùng với mã sản phẩm trong database!!!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanlyXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBxoaActionPerformed

    private void jBlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlammoiActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn format lại không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            jTtimkiem.setText("");
        }
    }//GEN-LAST:event_jBlammoiActionPerformed

    private void jBtimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtimkiemActionPerformed
        // TODO add your handling code here:
        String tenxe = jTtimkiem.getText();
        try {
            show_timkiem(tenxe);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanlyXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtimkiemActionPerformed

    private void jTqlxeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTqlxeKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN)
        {
        jTmaxe.setEditable(false);
        jTmaxe.setText((String) jTqlxe.getValueAt(jTqlxe.getSelectedRow(),0));
        jTtenxe.setText((String) jTqlxe.getValueAt(jTqlxe.getSelectedRow(),1));
        jThangxe.setText((String) jTqlxe.getValueAt(jTqlxe.getSelectedRow(),2));
        jTgiathanh.setText((String) jTqlxe.getValueAt(jTqlxe.getSelectedRow(),3));
        }
    }//GEN-LAST:event_jTqlxeKeyReleased

    //Đếm số dòng có trong bảng Products
    public int Dem() throws ClassNotFoundException {
        int dem = 0;
        try {
            Connect pt = new Connect();
            ResultSet rs = pt.GetData("Products");
            while (rs.next()) {
                dem++;//Đếm số dòng trong table Products
            }

            pt.Close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
        return dem;
    }

    public void ShowTable() {
      //  Hiển thị dữ liệu lên table;
        DefaultTableModel model = (DefaultTableModel) jTqlxe.getModel();
         model.setRowCount(0);
         model.setRowCount(50);
        // model.setRowCount(Dem());//Thiết lập số dòng của jtable = số dòng của bảng của DataBase
        try {
            Connect pt = new Connect();
            ResultSet rs = pt.GetData("Products");
            int i = 0;
            while (rs.next()) {                
                jTqlxe.setValueAt(rs.getString("ID"), i, 0);
                jTqlxe.setValueAt(rs.getString("TenXe"), i, 1);
                jTqlxe.setValueAt(rs.getString("HangXe"), i, 2);
                jTqlxe.setValueAt(rs.getString("GiaThanh"), i, 3);
                i++;
            }
            pt.Close();
        } catch (SQLException sqlException) {
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanlyXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void suaDL() {
        Connect pt;
        try {
            pt = new Connect();
            pt.Update(jTmaxe.getText(), jTtenxe.getText(), jThangxe.getText(), Integer.parseInt(jTgiathanh.getText()));
            pt.Close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanlyXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Show_Detail() {
        try {
            Connect pt = new Connect();
       //     ResultSet rs = pt.GetData("Products");
            int i = jTqlxe.getSelectedRow();

            jTmaxe.setText((String) jTqlxe.getValueAt(i, 0));
            jTtenxe.setText((String) jTqlxe.getValueAt(i, 1));
            jThangxe.setText((String) jTqlxe.getValueAt(i, 2));
            jTgiathanh.setText((String) jTqlxe.getValueAt(i, 3));

            pt.Close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanlyXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Delete(String maxe) {

        Connect pt;
        try {
            pt = new Connect();
            pt.Delete(maxe);
            pt.Close();
        } catch (SQLException sqlException) {
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanlyXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Clear_Table() throws ClassNotFoundException {
        DefaultTableModel model = (DefaultTableModel) jTqlxe.getModel();
        model.setRowCount(0);
        model.setRowCount(Dem());
    }
    
    public void Insert() {
        String maxe = jTmaxe.getText();
        String tenxe = jTtenxe.getText();
        String hangxe = jThangxe.getText();
        int giathanh = Integer.parseInt(jTgiathanh.getText());
        Connect pt;
        try {
            pt = new Connect();
            pt.Insert(maxe, tenxe, hangxe, giathanh);
            pt.Close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanlyXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void show_timkiem(String tenxe) throws ClassNotFoundException {
        Clear_Table();
        try {
            Connect pt = new Connect();
            ResultSet rs = pt.GetData_TK(tenxe);
            int i = 0;
            while (rs.next()) {
                jTqlxe.setValueAt(rs.getString("MaXe"), i, 0);
                jTqlxe.setValueAt(rs.getString("TenXe"), i, 1);
                jTqlxe.setValueAt(rs.getString("HangXe"), i, 2);
                jTqlxe.setValueAt(rs.getString("GiaThanh"), i, 3);
                i++;
            }
            pt.Close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanlyXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
    
    private boolean check(String maxe) throws ClassNotFoundException {
        boolean check = false;
        try {
            Connect pt = new Connect();

            ResultSet rs = pt.GetData("Products");
            while (rs.next()) {
                if (rs.getString(1).equals(maxe) == true) {
                    check = true;
                }
            }
            pt.Close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
                }
        return check;
    }    
    
    
    /**
     * @param args the command line arguments
     */
    //<editor-fold defaultstate="collapsed" desc="comment">
    /*public*/
//</editor-fold>
    public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(QuanlyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(QuanlyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(QuanlyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(QuanlyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanlyXe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBlammoi;
    private javax.swing.JButton jBsua;
    private javax.swing.JButton jBthem;
    private javax.swing.JButton jBtimkiem;
    private javax.swing.JButton jBxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTgiathanh;
    private javax.swing.JTextField jThangxe;
    private javax.swing.JTextField jTmaxe;
    private javax.swing.JTable jTqlxe;
    private javax.swing.JTextField jTtenxe;
    private javax.swing.JTextField jTtimkiem;
    // End of variables declaration//GEN-END:variables
}
